apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-professor-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: chaos-professor-operator
  template:
    metadata:
      labels:
        name: chaos-professor-operator
    spec:
      serviceAccountName: chaos-professor-operator
      containers:
        - name: chaos-professor-operator
          # Replace this with the built image name
          image: quay.io/openshift-examples/chaos-professor-operator:master
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "chaos-professor-operator"
