kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "chaos-professor.fullname" . }}
  labels:
{{ include "chaos-professor.labels" . | indent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "chaos-professor.fullname" . }}
